PRAGMA journal_mode=WAL;
create table programs( id integer primary key, nid integer, tsid integer, service_id integer, service_name integer, service_name_raw blob, event_id integer, program_name text, program_name_raw blob, start integer, end integer, actual_start integer, actual_end integer, genre text, genre_raw blob, program_text text, program_text_raw blob, program_detail text, program_detail_raw blob, record_filename text, future integer );
create table changelog( id integer primary key, time integer, actual_time integer, nid integer, tsid integer, service_id integer, service_name integer, service_name_raw blob, event_id integer, program_name text, program_name_raw blob, start integer, end integer, genre text, genre_raw blob, program_text text, program_text_raw blob, program_detail text, program_detail_raw blob, record_filename text );

create index idx_programs_nid on programs(nid);
create index idx_programs_tsid on programs(tsid);
create index idx_programs_nid_tsid on programs(nid, tsid);
create index idx_programs_service_id on programs(service_id);
create index idx_programs_event_id on programs(event_id);
create index idx_programs_service_id_event_id on programs(service_id, event_id);
create index idx_programs_service_name on programs(service_name);
create index idx_programs_program_name on programs(program_name);
create index idx_programs_start on programs(start);
create index idx_programs_end on programs(end);
create index idx_programs_start_end on programs(start, end);
create index idx_programs_actual_start on programs(actual_start);
create index idx_programs_actual_end on programs(actual_end);
create index idx_programs_actual_start_actual_end on programs(actual_start, actual_end);
create index idx_programs_genre on programs(genre);
create index idx_programs_program_text on programs(program_text);
create index idx_programs_program_detail on programs(program_detail);
create index idx_programs_record_filename on programs(record_filename);
create index idx_programs_future on programs(future);

create index idx_changelog_time on changelog(time);
create index idx_changelog_actual_time on changelog(actual_time);
create index idx_changelog_nid on changelog(nid);
create index idx_changelog_tsid on changelog(tsid);
create index idx_changelog_nid_tsid on changelog(nid, tsid);
create index idx_changelog_service_id on changelog(service_id);
create index idx_changelog_event_id on changelog(event_id);
create index idx_changelog_service_id_event_id on changelog(service_id, event_id);
create index idx_changelog_service_name on changelog(service_name);
create index idx_changelog_program_name on changelog(program_name);
create index idx_changelog_start on changelog(start);
create index idx_changelog_end on changelog(end);
create index idx_changelog_start_end on changelog(start, end);
create index idx_changelog_genre on changelog(genre);
create index idx_changelog_program_text on changelog(program_text);
create index idx_changelog_program_detail on changelog(program_detail);
create index idx_changelog_record_filename on changelog(record_filename);
